name: Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install TaskChain
        run: |
            python -m pip install --upgrade poetry
            poetry config virtualenvs.create false
            poetry install
      - name: Run tests
        run: make test
